package kr.kro.greenlava.demo.global.api;

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import groovy.util.logging.Slf4j;
import io.jsonwebtoken.SignatureAlgorithm;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import kr.kro.greenlava.demo.global.constant.Constant;
import kr.kro.greenlava.demo.global.util.jwt.JwtProvider;

@Slf4j
@RestController
@RequestMapping("/v1/jwt")
@Tag(name = "jwt", description = "jwt 발급용 API")
public class JwtRestApi {
	private static Logger logger = LoggerFactory.getLogger(JwtRestApi.class);
	
	@Operation(summary = "get jwt token", description = "return jwt token generated by yml config")
	@GetMapping("token")
	public ResponseEntity<Map<String, Object>> getToken() {
		String token = "";
		Map<String, Object> result = new HashMap<>();
		
		try {
			token = JwtProvider.generateToken(1800, SignatureAlgorithm.HS256, Constant.JWT_KEY, Constant.JWT_SECRET);
		} catch (Exception e) {
			logger.debug(e.getMessage());
			return ResponseEntity.badRequest().build();
		}
		
		if(token == null || token.isEmpty()) {
			return ResponseEntity.notFound().build();
		}
		
		result.put("token", token);
		
		return ResponseEntity.ok().body(result);
	}

}
